name: CD

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:

    build:
        runs-on: self-hosted

        steps:
            - name: Checkout
              run: git pull origin master

            - name: Validate composer.json and composer.lock
              run: pwd && composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: CS
              run: composer cs
