name: CD

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:

    deploy:
        runs-on: self-hosted

        steps:
            - name: Move to folder
              run: cd /var/www/project-release.stacha.dev/web

            - name: Checkout
              run: git pull origin master

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Reload database
              run: composer orm:remove && composer orm:create
