name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run: 
   shell: bash -l {0}
   working-directory: /var/www/project-release.stacha.dev/web

jobs:
  deploy:
      runs-on: self-hosted
      steps:
          - name: Checkout
            run: git pull origin master --recurse-submodules

          - name: Install dependencies
            run: composer install --prefer-dist --no-progress --no-suggest
          
          - name: nvm
            shell: bash -l {0}
            run: nvm -v
          
          - name: Reinstall instance
            working-directory: /var/www/project-release.stacha.dev/web/bin
            run: ./install.sh
