name: Deploy

on:
  workflow_dispatch:
    inputs:
      instance:
        description: 'Instance'
        required: true
        default: 'pc.stacha.dev'  

defaults:
  run:
   shell: bash -ieo pipefail {0}

jobs:
  deploy:
      runs-on: self-hosted
      steps:
        - name: Go to
          run: cd /var/www/${{ github.event.inputs.instance }}/web
          
        - uses: actions/checkout@v2
          with:
            ref: master
          
        - name: Install
          run: ./bin/install.sh ${{ secrets.DB_USER }} ${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }}
