name: CI

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    test:
        runs-on: self-hosted
        
        steps:
            - name: Checkout
              run: cd back-end
            
            - name: Validate composer.json and composer.lock
              run: pwd && composer validate
              
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: CS
              run: composer cs
