name: CI

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    test:
        runs-on: self-hosted
        
        steps:
            - name: Checkout
              run: if [ ! -d "back-end" ]; then git clone git@github.com:Stacha-dev/back-end.git; fi && cd back-end
            
            - name: Validate composer.json and composer.lock
              run: composer validate
              
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: CS
              run: composer cs
